Use deletion_policy = "ABANDON" for private VPC connection
This addresses the following error (encountered during "terraform destroy"):
```
Error: Unable to remove Service Networking Connection, err: Error waiting for Delete Service Networking Connection: Error code 9, message: Failed to delete connection; Producer services (e.g. CloudSQL, Cloud Memstore, etc.) are still using this connection.
```

With "google" provider version 5 and up, the deletion of google_service_networking_connection uses "deleteConnection" (which does a thorough clean-up of resources) instead of "removePeering" (which doesn't do a thorough clean-up of resources).
However, when using CloudSQL, deleteConnection needs to wait a few days (until residual CloudSQL resources have been cleaned up).

In other words, users would have to:
1. "terraform destroy" and have it commence (but not complete) deletion of CloudSQL resources, but fail as soon as it tries to delete the google_service_networking_connection resource.
2. Wait a few days until CloudSQL resources have been cleaned up.
3. "terraform destroy" again and have it delete google_service_networking_connection (and remaining resources).

The workaround is to abandon the google_service_networking_connection resource altogether (i.e., not delete it).

removePeering (used by older provider versions) didn't do a thorough clean-up of resources anyway, so the use of `deletion_policy = "ABANDON"` here doesn't introduce any new problems.

More info:
- b/308248337#comment7
- https://github.com/hashicorp/terraform-provider-google/issues/16275